update action

diff --git a/.github/workflows/kargo-render.yaml b/.github/workflows/kargo-render.yaml
--- a/.github/workflows/kargo-render.yaml
+++ b/.github/workflows/kargo-render.yaml
@@ -30,9 +30,9 @@ jobs:
         echo "GITHUB_REF_TYPE=${GITHUB_REF_TYPE}"
         echo "GITHUB_WORKFLOW_SHA=${GITHUB_WORKFLOW_SHA}"
 
-        echo "github.event.pull_request.base.sha=${github.event.pull_request.base.sha}" || echo fail
-        echo "github.sha=${github.sha}" || echo fail
+        echo "github.event.pull_request.base sha=$(jq -r .pull_request.base.sha < $GITHUB_EVENT_PATH)" || echo fail
         echo "from GITHUB_EVENT_PATH: $(cat $GITHUB_EVENT_PATH | jq -r .pull_request.head.sha)" || echo fail
+        echo "github.sha=${github.sha}" || echo fail
 
     - name: Render and Commit Manifests
       uses: akuity/kargo-render-action@v0.1.0-rc.40
